// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/nginxinc/kubernetes-ingress/pkg/client/clientset/versioned/typed/dos/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAppprotectdosV1beta1 struct {
	*testing.Fake
}

func (c *FakeAppprotectdosV1beta1) DosProtectedResources(namespace string) v1beta1.DosProtectedResourceInterface {
	return &FakeDosProtectedResources{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAppprotectdosV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
