[build]
  base = "docs/"
  publish = "public"
  command = "hugo --gc -b $DEPLOY_PRIME_URL/nginx-ingress-controller"

[build.environment]
  HUGO_VERSION = "0.80.0"

[context.development]
  command = "hugo --gc -e development"

[context.staging]
  command = "hugo --gc -e staging"

[context.production]
  command = "hugo --gc -e production"

[context.deploy-preview]
  command = "hugo --gc -b $DEPLOY_PRIME_URL/nginx-ingress-controller"

[context.branch-deploy]
  command = "hugo --gc -b $DEPLOY_PRIME_URL/nginx-ingress-controller"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-ingress-controller/"
  status = 301
  force = true


[[redirects]]
  from = "/nginx-ingress-controller/robots.txt"
  to = "https://docs.nginx.com/robots.txt"
  status = 301
  force = true

[[redirects]]
  from = "*"
  to = "/nginx-ingress-controller/404.html"
  status = 404


