baseURL = "https://docs.nginx.com/nginx-ingress-controller"
title = "NGINX Ingress Controller"
publishDir = "public/nginx-ingress-controller"
canonifyURLs = false

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
