annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 15.1.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
engine: gotpl
home: https://www.keycloak.org
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
  - keycloak
  - access-management
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: keycloak
sources:
  - https://github.com/bitnami/bitnami-docker-keycloak
  - https://github.com/keycloak/keycloak
version: 5.2.8
