// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// DosProtectedResourceListerExpansion allows custom methods to be added to
// DosProtectedResourceLister.
type DosProtectedResourceListerExpansion interface{}

// DosProtectedResourceNamespaceListerExpansion allows custom methods to be added to
// DosProtectedResourceNamespaceLister.
type DosProtectedResourceNamespaceListerExpansion interface{}
