//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApDosMonitor) DeepCopyInto(out *ApDosMonitor) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApDosMonitor.
func (in *ApDosMonitor) DeepCopy() *ApDosMonitor {
	if in == nil {
		return nil
	}
	out := new(ApDosMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosProtectedResource) DeepCopyInto(out *DosProtectedResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosProtectedResource.
func (in *DosProtectedResource) DeepCopy() *DosProtectedResource {
	if in == nil {
		return nil
	}
	out := new(DosProtectedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DosProtectedResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosProtectedResourceList) DeepCopyInto(out *DosProtectedResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DosProtectedResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosProtectedResourceList.
func (in *DosProtectedResourceList) DeepCopy() *DosProtectedResourceList {
	if in == nil {
		return nil
	}
	out := new(DosProtectedResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DosProtectedResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosProtectedResourceSpec) DeepCopyInto(out *DosProtectedResourceSpec) {
	*out = *in
	if in.ApDosMonitor != nil {
		in, out := &in.ApDosMonitor, &out.ApDosMonitor
		*out = new(ApDosMonitor)
		**out = **in
	}
	if in.DosSecurityLog != nil {
		in, out := &in.DosSecurityLog, &out.DosSecurityLog
		*out = new(DosSecurityLog)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosProtectedResourceSpec.
func (in *DosProtectedResourceSpec) DeepCopy() *DosProtectedResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DosProtectedResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosSecurityLog) DeepCopyInto(out *DosSecurityLog) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosSecurityLog.
func (in *DosSecurityLog) DeepCopy() *DosSecurityLog {
	if in == nil {
		return nil
	}
	out := new(DosSecurityLog)
	in.DeepCopyInto(out)
	return out
}
